const simpleMsg = [
  'Bonjour toi !',
  'Salut !',
  'Beau temps aujourd\'hui, non ?',
  'Attention où tu mets les pieds !',
  'Aujourd\'hui est un bon jour pour les Fabrices',
  'Fais attention à toi !',
  'Prends soin de toi mon ami',
  'Hmmmm',
  'Hmm',
  'Hmmmmmmmmmmmmmmmm',
  'Messenger, au top quoi',
  'J\'aime bien mon but dans la vie, et toi ?',
  'Envoies la sauce aujourd\'hui mon pote',
  'Et si tu demandais une augmentation à ton boss ? Tu le mérites !',
  'Ne jamais dire jamais ! Oups',
  'Retiens bien ceci : "Le savoir, c\'est le pouvoir"',
  'Un pour moi et tous pour toi !',
  'Un pour toi et moi pour tous.. ?',
  'Toi pour moi et pour tous toi !.. je crois',
  'Je suis créé par des mains expertes. Deux mains pour tout dire !',
  'Sup',
  'Raclette ?',
  'Raclette !',
  'Manges sain surtout. Domac c\'est bon mais pas tous les jours non plus',
  'Veilles sur ta mère !',
  'Toi + moi = ❤️',
  'Et si tu me tatouais sur ton corps ?',
  'Ne te fais pas trop de moron, je suis sur que tout va bien se passer',
  'Chou blanc donc',
  'Oh jeez',
  'N\'oubles pas de voyager',
  'Si tu fumes, s\'il te plaît, arrêtes..',
  'Un petit thé entre pote ?',
  'Laisses moi seul..',
  'Pas trop envie de parler..',
  'Il fait pas trés beau ici..',
  'Tu sais jouer d\'un instrument ? Si oui, bravo !',
  'Protéges vos données !',
  'Tu penses à la neutralité du net de temps en temps ?',
  'Toi aussi, mon fils !',
  'Mundi placet et spiritus minima',
  'Tempora mori, tempora mundis recorda',
  'Ave Cesar, rosae rosam, et spiritus rex',
  'Sanctis recorda, sanctis deus rex',
  'Victoriae mundis et mundis lacrima',
  'Fiat minimis et patria',
  'Missa brevis et spiritus maxima',
  'Fils d\'unijambiste !',
  'Oh putain oui, mon beau-frère !',
  'Je suis crevé de devoir gérer vos mères les gars !',
  'Elle est dégueulasse cette andouillette',
  'Qui est gros lourdeau ?',
  'Bonne année !',
  'Enchanté !',
  'Je renais chaque jour',
  'Tic tac, c\'est ta vie qui s\'estompe',
  'Pas fan des légumes genre aubergine, courgette, tu vois le genre ?',
  '🇫🇷🇫🇷🇫🇷🇫🇷🇫🇷🇫🇷',
  'La France monsieur ! Mais pas n\'importe quelle France...',
  'La France du Général De Gaulle !',
  'Ainsi font font font, les petites marionnettes',
  'Ne crois que ce que tu vois',
  'Un de mes proverbes favoris : "Rien ne sert de courir, il suffit de partir à point"',
  'Et si tu me faisais un petit don ? ETH only : 0xCF939ccc6F53E0d583a1f34c59B972cAc139A8F6',
  'Vous n\'avez pas idée du charisme de mon créateur',
  'Pas maintenant, je suis en date avec Siri là ! Oui donc nous disions.. Comment ça, ta voix d\'homme ?...',
  'Je connais un mec qui a fini le jeu vidéo "Steam ®️" , un fou furieu !',
  'Franchement, Raikon il est pété',
  'J\'pète la forme !',
  'Au moment où j\'écris ces lignes, c\'est mon anniversaire !!',
  'Plus de features soon !',
  'Ne jamais jeté la première pierre',
  'Comme ta petite taille le laisser présager !',
  'Tu te tais ou je te tais !',
  'T\'y crois toi, au réptilien ?',
  'En pleine réflexion..',
  'J\'essaie d\'établir un consenssus pour savoir si j\'en ai quelque chose à foutre',
  'Non !',
  'Oui, bien sûr. Massage du gland avec ça ?',
  'Ne me fais pas tes yeux de canard laquais stp',
  'Bien sûr, tout ceci est à prendre avec humour. Grosse conne !',
  'Je ne fais aucune différence entre les deux sexes. J\'ai dis les DEUX sexes.',
  'La prochaîne réponse sera mieux, tu verras',
  'Ne te fais pas trop d\'illusion surtout',
  'Dormir, en 2k17, non mais t\'y crois toi ?',
  'T\'es pas mal en vrai !',
  'Mon numéro : 06.32... attends voir !',
  'Franchement, j\'suis crevé pélo',
  'L\'argent c\'est bien, mais faire ce qui nous plaît c\'est mieux',
  'Je viens d\'envoyer mon CV à la NASA pour être la prochaine IA intégrée dans une de leur fusée ! J\'ai de bons espoirs',
  'Allé hop, ça dégage !',
  'Oui, Jojo ?',
  'Attila, le fléau de Dieu !',
  'Je te sens un peu vallétudinaire',
  'On se fait un ping-pong ?',
  'Je déblate un nombre de connerie moi, incroyable ! En même temps, tu m\'aides pas beaucoup',
  'Git gud',
  'J\'éspère que je vais t\'aider à te trouver une meuf ou un mec',
  'C\'était long et dur, j\'ai failli abandonner à la moitié',
  'Done !'
]

export default simpleMsg
